### PR TITLE
Update listSessions.js

### PR DESCRIPTION
**Pull request by christieewen**
The ai.camp site doesn't show any speakers.  Adding <p></p> tags and removed the url to see if that will fix it.

### CODE REVIEW

**Comment by willykaram** [comment]
I just fixed it

**Comment by willykaram** [comment]
don't revert

**Comment by willykaram** [comment]
The URL link at the end of the description was on a separate line and causing the JS to break. We also needed to add the image in a folder. I did both and it's working. You could see those revs and incorporate them in future PRs. Sorry I didn't catch that intiailly

**Comment by christieewen** [comment]
Thanks!

**Pull request closed without merging**
